services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microsservice_db
    ports:
      - "5433:5432"

  Microsservice-db-service:
    build: ./microsservice-db
    ports:
      - "8081:8081"
    depends_on:
      - db

  Microsservice-RESTful-service:
    build: ./microsservice-RESTful
    ports:
      - "8082:8082"